---
 - hosts: all
   become: true
   tasks:

     - name: verificando status do serviço nginx
       command: service apache2 status

     - name: verificando esculta na porta 80 
       wait_for: port=80 timeout=1

     - name: verificando status do serviço mysql 
       command: service mysql status

     - name: verificando esculta na porta 3306 
       wait_for: port=3306 state=drained 
